// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp( options: DefaultFirebaseOptions.currentPlatform,)then(
/// firebaseapp value) => get.put(authenticarepository()),
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClLeFjNM1c37MUGzozSxMAmIaXBAYaibA',
    appId: '1:181783457456:web:f22a47154d179862d4d575',
    messagingSenderId: '181783457456',
    projectId: 'segarku-27cf6',
    authDomain: 'segarku-27cf6.firebaseapp.com',
    storageBucket: 'segarku-27cf6.firebasestorage.app',
    measurementId: 'G-Y1DHH3K82E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMKnw4jGmXNCuCgH0zbIaWlKxszJp3SXk',
    appId: '1:181783457456:android:147e2e191a75dde8d4d575',
    messagingSenderId: '181783457456',
    projectId: 'segarku-27cf6',
    storageBucket: 'segarku-27cf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl9JcMqqK6VtMLMPfQHRue77TsuSP2xS8',
    appId: '1:181783457456:ios:f98a939c543929dbd4d575',
    messagingSenderId: '181783457456',
    projectId: 'segarku-27cf6',
    storageBucket: 'segarku-27cf6.firebasestorage.app',
    androidClientId: '181783457456-k1ml9tvcotr2db8h3j2bmvnvatpsdbiu.apps.googleusercontent.com',
    iosClientId: '181783457456-1g2ehfaje3127gsb79gscauok6gtl0o2.apps.googleusercontent.com',
    iosBundleId: 'com.example.segarku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl9JcMqqK6VtMLMPfQHRue77TsuSP2xS8',
    appId: '1:181783457456:ios:f98a939c543929dbd4d575',
    messagingSenderId: '181783457456',
    projectId: 'segarku-27cf6',
    storageBucket: 'segarku-27cf6.firebasestorage.app',
    androidClientId: '181783457456-k1ml9tvcotr2db8h3j2bmvnvatpsdbiu.apps.googleusercontent.com',
    iosClientId: '181783457456-1g2ehfaje3127gsb79gscauok6gtl0o2.apps.googleusercontent.com',
    iosBundleId: 'com.example.segarku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClLeFjNM1c37MUGzozSxMAmIaXBAYaibA',
    appId: '1:181783457456:web:938be6445f0bdbd0d4d575',
    messagingSenderId: '181783457456',
    projectId: 'segarku-27cf6',
    authDomain: 'segarku-27cf6.firebaseapp.com',
    storageBucket: 'segarku-27cf6.firebasestorage.app',
    measurementId: 'G-L0GPGLYTKC',
  );

}